### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by Huddie** [bitrise-steplib/steps-script-runner#10]
Does this allow for command line arguments? If so how?

**Comment by bitce** [comment]
Hey @Huddie , sorry for the late reply!

What would be your use case exactly? Would you like to use a bash script for another step to call for later? You may also be able to set the value as an env var. 

Let us know!

**Comment by Huddie** [comment]
@bitce I ended up using the general script step (Where you can type anything) and saving the variables and what not. 
This step is nice but if you want to pass in arguments, lt didnt seem possible.

Example:
php foo.php $SAVED_VARIABLE . Or at least I couldnt figure out how to accomplish this.

**Comment by bitce** [comment]
Hi @Huddie !

Sorry, I was meaning you could do so with the general script step, this one runs a script from file so you can't specify that unfortunately.

Glad to hear you've gotten around it though!

**Comment by josinaldobarbosa** [comment]
Hi @bitce
I don't see the reason for this limitation, I have several shared scripts that can be in different places, either in Ci, locally or in different workflows that make more sense to use parameters and I am have used the step script for that in these cases, but it would make it easier to use just that step.

sorry the english

**Comment by bitce** [comment]
Hi @josinaldobarbosa! No worries, but I don't clearly understand your problem, can you explain? 

You can easily get around this limitation by using the regular script step

**Comment by luongvo** [comment]
I agree with @josinaldobarbosa that this step should support for bash arguments to make it more flexible. Currently, I'm facing the same issue on the same script but would like to accept different arguments in each workflow. How can I do that? I have to make a workaround to duplicate the script file and switch by each workflow.

**Comment by stojan26** [comment]
I am using this step to run a python script. I need to make the script configurable so I wanted to add arguments to it. But then it's impossible to run it using this step.

I am aware of the workaround, to write bash and pass the arguments that way, however it defeats the purpose. I wrote the script in python to avoid bash. And now in addition to YAML and Python I have to add bash to the mix.

Making it possible for this step to support arguments will make it more flexible and re-usable.

Thank you.

**Comment by cathyharmon** [comment]
Hello,

I will submit this as a feature request.

Thanks!
cathy
